### ISSUE TITLE
Kanban board Project Setup (Team of 3)

### ISSUE THREAD

**Issue by Mo7amedSMahdi** [Mo7amedSMahdi/catalog-of-things#43]
Hi all,
This is the project link for our kanban board with all tasks assigned.

We are a group of 3 students:
- @Melaku05 as Team member #1.
- @Mo7amedSMahdi as Team member #2.
- @YannickZahinda as Team member #3.

https://github.com/Mo7amedSMahdi/catalog-of-things/projects/1

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi @team,  

Good luck!

## Good Points 👍 
- Kanban is set up correctly ✔️ 


![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
